# Autogenerated wrapper script for libwatcher_jll for x86_64-w64-mingw32-cxx11
export libwatcher

using LibUV_jll
JLLWrappers.@generate_wrapper_header("libwatcher")
JLLWrappers.@declare_library_product(libwatcher, "libwatcher.dll")
function __init__()
    JLLWrappers.@generate_init_header(LibUV_jll)
    JLLWrappers.@init_library_product(
        libwatcher,
        "bin\\libwatcher.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
