# Autogenerated wrapper script for libwatcher_jll for x86_64-linux-gnu-cxx03
export libwatcher

using LibUV_jll
JLLWrappers.@generate_wrapper_header("libwatcher")
JLLWrappers.@declare_library_product(libwatcher, "libwatcher.so")
function __init__()
    JLLWrappers.@generate_init_header(LibUV_jll)
    JLLWrappers.@init_library_product(
        libwatcher,
        "lib/libwatcher.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
